### ISSUE TITLE
[question] 需要管理员权限是正常的吗？

### ISSUE THREAD

**Issue by Ethkuil** [euxcet/thulearn2018#10]
注：给予管理员权限后能正常工作，只是有点疑惑为什么会需要管理员权限。

无管理员权限时的报错（Git Bash, PowerShell, CMD 均如此）：

```txt
$ learn download
Traceback (most recent call last):
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\Scripts\learn.exe\__main__.py", line 7, in <module>
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\site-packages\thulearn2018\learn.py", line 20, in download
    learn.set_semester(semester)
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\site-packages\thulearn2018\browser.py", line 77, in set_semester
    os.symlink(os.path.join(settings.temp_path, self.semester+".txt"),
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\OS\\AppData\\Roaming\\thulearn2018\\2023-2024-1.txt' -> 'C:\\Users\\OS\\AppData\\Roaming\\thulearn2018\\local.txt'
```

补充：

- 在下载完成后再次执行 `learn download` 会报完全一样的错误。
- 再执行 `learn ddl` 也需要管理员权限。

**Comment by YuruiHong** [comment]
不正常，这是由于Windows 10及以下默认需要以管理员权限创建软链接（即使操作的是用户目录）导致的。具体解决方法是开启开发者模式，详情参见[https://stackoverflow.com/questions/58038683/allow-mklink-for-a-non-admin-user](https://stackoverflow.com/questions/58038683/allow-mklink-for-a-non-admin-user)。thulearn2018的下载记录功能是分学期存储的，这使得每次使用`download`和`ddl`功能时，需要修改一个软链接的指向，所以需要有创建软链接权限。

据我所知，Windows 11已经移除了上述限制，因此理论上不会遇到这个问题

**Comment by Ethkuil** [comment]
> 据我所知，Windows 11已经移除了上述限制，因此理论上不会遇到这个问题

那就是理论不符合实际了，因为我的系统就是 Windows11 qwq。Version: 10.0.22621 Build 22621

**Comment by Ethkuil** [comment]
> 这使得每次使用download和ddl功能时，需要修改一个软链接的指向，所以需要有创建软链接权限。

感觉似乎不创建软链接也能实现同样功能

**Comment by YuruiHong** [comment]
> > 据我所知，Windows 11已经移除了上述限制，因此理论上不会遇到这个问题
> 
> 那就是理论不符合实际了，因为我的系统就是 Windows11 qwq。Version: 10.0.22621 Build 22621

非常抱歉，因为我现有的Windows测试环境仅有Win 10，因为一直开着开发者模式自己确实无法发现问题，而Win 11的结论我只是阅读了文档，没有测试过。我已经发步了2.3.1版本对Windows实现为硬链接，在自己的测试环境下通过。如果仍然没有解决你的问题，请重新开启这个issue。
