### ISSUE TITLE
[maybe bug] Fail to submit hw

### ISSUE THREAD

**Issue by Ethkuil** [euxcet/thulearn2018#11]
终端输出复制如下：

```
OS@ETHKUIL-16ZB90Q MINGW64 /d/home/projects/大三上/计算机组成原理/homework/第三次小作业
$ learn submit <stuID_name_csapp3.pdf>
Traceback (most recent call last):
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\Scripts\learn.exe\__main__.py", line 7, in <module>
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\site-packages\thulearn2018\learn.py", line 71, in submit
    learn.upload(xszyid, name, m)
  File "C:\Users\OS\AppData\Local\Programs\Python\Python310\lib\site-packages\thulearn2018\browser.py", line 201, in upload
    if response.status_code == 200:
AttributeError: 'bytes' object has no attribute 'status_code'
```

**Comment by YuruiHong** [comment]
已修复，之前误将开发到一半的提交过期提醒功能上传到PyPI，导致该错误。现在，试图提交已过期作业不会显示done，而会提示作业可能已过期并打印response。
