### ISSUE TITLE
下载某门课程时报错，程序终止

### ISSUE THREAD

**Issue by YuruiHong** [euxcet/thulearn2018#16]
```bash
$ learn download -s 2020-2021-1 -o /mnt/onedrive2/onlineOnly/prevmajor/2020-2021-1 -i "微积分A(1)" --download-submission
Check 微积分A(1)
Traceback (most recent call last):
  File "/home/hyr/.local/bin/learn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/hyr/.local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyr/.local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/hyr/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyr/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyr/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyr/.local/lib/python3.11/site-packages/thulearn2018/learn.py", line 27, in download
    groups = learn.get_files_id(lesson[0])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyr/.local/lib/python3.11/site-packages/thulearn2018/browser.py", line 124, in get_files_id
    files_id = [row["id"] for row in files["object"]["rows"]]
                                     ~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

```

**Comment by YuruiHong** [comment]
经过调查，发现该课程在网络学堂上的归档缺少 “课程文件”“课程信息”等所有内容卡片，仅可查看作业提交与批改情况，在使用`wlkcid`进行课程文件查询时，返回这样的内容：

```
{'result': 'error', 'msg': '您没有访问此功能的权限！', 'object': None}
```

而非`files["object"]["rows"]`为空列表的正常无课程文件的响应内容。据此推测，应该是教师端主动禁止了对已归档课程文件的访问，故计划的处理方法是加入对`files["object"]`为空的特判，视为空文件列表。
